services:
  db:
    image: postgres:16
    container_name: postgresPB
    restart: unless-stopped
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"        # lub "5433:5432" jeśli konflikt
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d pgdb"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - internal_net


  pgadmin:
    image: dpage/pgadmin4:8
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_haslo
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal_net

volumes:
  pgdata:

networks:
  internal_net:
    driver: bridge