-- USERS
ALTER table public.users
  ALTER COLUMN id TYPE BIGINT;

-- PROJECTS
ALTER TABLE public.projects
  ALTER COLUMN id TYPE BIGINT;

-- ISSUES
ALTER TABLE public.issues
  ALTER COLUMN id TYPE BIGINT,
  ALTER COLUMN project_id TYPE BIGINT,
  ALTER COLUMN assignee_id TYPE BIGINT;

-- COMMENTS
ALTER TABLE public.comments
  ALTER COLUMN id TYPE BIGINT,
  ALTER COLUMN issue_id TYPE BIGINT,
  ALTER COLUMN author_id TYPE BIGINT;
